name: Daily Garmin Sync

on:
  schedule:
    - cron: '0 3 * * *'  # runs daily at 03:00 UTC
  workflow_dispatch:      # allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Garmin Download
      run: |
        python garmin_download.py
      env:
        GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
        GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
