name: Garmin DB CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # runs daily at 04:00 UTC

jobs:
  garmin-process:
    runs-on: ubuntu-latest

    env:
      GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
      GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
      GARMINDATA_DIR: ./data
      GARMIN_LATEST_ACTIVITY_COUNT: 10
      GARMIN_ALL_ACTIVITY_COUNT: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Garmin DB sync
        run: |
          python your_script.py --download --import --analyze --all --latest --overwrite
